name: "Generate C4 Model"
description: "Convert a Structurizr DSL file to PlantUML image files"

inputs:
  source-path:
    description: "The path to the Structurizr DSL file"
    required: true
  target-path:
    description: "The path to the directory in which to place the C4 model artifacts"
    required: true
    default: .github/actions/dist

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.source-path }}
    - ${{ inputs.target-path }}
